stages:
  ingest:
    cmd: python src/data_ingestion.py
    deps:
    - data/Breast_cancer_dataset.csv
    - src/data_ingestion.py
    outs:
    - data/interim/cleaned.csv
  preprocess:
    cmd: python src/data_preprocessing.py
    deps:
    - data/Breast_cancer_dataset.csv
    - src/data_preprocessing.py
    outs:
    - data/processed/X.csv
    - data/processed/y.csv
